# Generated by Django 3.2.4 on 2021-06-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_img', models.FileField(blank=True, null=True, upload_to='profile_img')),
            ],
        ),
    ]
